# Generated by Django 6.0.4 on 2026-05-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description_orderitem_price_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
