# Generated by Django 6.0.4 on 2026-05-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_cartitem_unique_together_alter_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
